server:
  port: 9020
spring:
  application:
    name: cds
---
spring:
  profiles: local
  data:
    redis:
      repositories:
        enabled: true
  redis:
    host: localhost
    port: 6379
    client-name: cds-microservice
  thymeleaf:
    reactive:
      max-chunk-size: 8192
---
spring:
  profiles: staging
  data:
    redis:
      repositories:
        enabled: true
  redis:
    host: berkeley-cds.redis.cache.windows.net
    port: 6379
    client-name: cds-microservice
    password: ${REDIS_PASSWORD:password}
  thymeleaf:
    reactive:
      max-chunk-size: 8192
---
spring:
  profiles: production
  data:
    redis:
      repositories:
        enabled: true
  redis:
    host: cds-redis-prod.redis.cache.windows.net
    port: 6379
    client-name: cds-microservice
    password: ${REDIS_PASSWORD:password}
  thymeleaf:
    reactive:
      max-chunk-size: 8192
---
spring:
  profiles: test
  data:
    redis:
      repositories:
        enabled: true
  redis:
    host: localhost
    port: 6379
    client-name: cds-microservice
  thymeleaf:
    reactive:
      max-chunk-size: 8192