server:
  port: 9020
spring:
  application:
    name: cds
---
spring:
  profiles: Development
  data:
    redis:
      repositories:
        enabled: true
  redis:
    host: localhost
    port: 6379
    client-name: cds-microservice
  thymeleaf:
    reactive:
      max-chunk-size: 8192

---
spring:
  profiles: Production
  data:
    redis:
      repositories:
        enabled: true
  redis:
    host: localhost
    port: 6379
    client-name: cds-microservice
  thymeleaf:
    reactive:
      max-chunk-size: 8192
---
