version: 2
jobs:
  build:
    docker:
      - image: maven:3.6.3-jdk-11
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{.Branch}}-{{checksum "pom.xml"}}
      - run:
          name: Run Tests
          command: |
            mvn clean test
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{.Branch}}-{{checksum "pom.xml"}}
      - run:
          name: Build And Push
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker build -t bockyanggoh/cds:latest .
            docker tag bockyanggoh/cds:latest bockyanggoh/cds:1.0.${CIRCLE_BUILD_NUM}
            docker push bockyanggoh/cds
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master