version: 2
jobs:
  build:
    docker:
      - image: maven:3.6.3-jdk-11
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{.Branch}}-{{checksum "pom.xml"}}
      - run:
          name: Run Tests
          command: |
            mvn clean test
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{.Branch}}-{{checksum "pom.xml"}}
  releaseArtifact:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: |
            docker build -t bockyanggoh/cds:latest .
            docker tag bockyanggoh/cds:latest bockyanggoh/cds:1.0.${CIRCLE_BUILD_NUM}
      - run:
          name: Push Images to DockerHub
          command: |
            echo $DOCKER_USERNAME
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push bockyanggoh/cds
  deploy:
    docker:
      - image: tinyworks/azcli:2.1.0-alpine
    steps:
      - run:
          name: Deploy to Azure Kubernetes
          command: |
            echo placeholder
workflows:
  version: 2
  build:
    jobs:
      - build
      - releaseArtifact:
          requires:
            - build
          context: dockerhub
      - deploy:
          requires:
            - releaseArtifact